-- Luo reference-taulu
CREATE TABLE reference (
    id SERIAL PRIMARY KEY,
    reftype VARCHAR(100),
    title VARCHAR(255),
    author VARCHAR(100),
    year VARCHAR(100),
    publisher VARCHAR(100),
    howpublished VARCHAR(100),
    institution VARCHAR(200),
    journal VARCHAR(100),
    volume VARCHAR(50),
    number VARCHAR(100),
    organization VARCHAR(100),
    school VARCHAR(100),
    series VARCHAR(100),
    issue VARCHAR(50),
    edition VARCHAR(100),
    chapter VARCHAR(50),
    pages VARCHAR(50),
    url VARCHAR(500),
    key VARCHAR(100),
    month VARCHAR(50),
    note TEXT, 
    misc_details TEXT,
    doi VARCHAR(150),
    address VARCHAR(200),
    type VARCHAR(50),
    booktitle VARCHAR(50),
    editor VARCHAR(50)

);
